Improve plugin structure

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -1,14 +1,23 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set +eu
+
+CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 if [[ -n ${GOOGLE_APPLICATION_SERVICE_ACCOUNT:-} ]]; then
   echo "~~~ :gcloud: Cleaning up Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT}"
   TOKEN_FILE=$($GOOGLE_APPLICATION_CREDENTIALS | jq -r .credentials_source.file)
   curl -X DELETE \
      -H "Authorization: Bearer $(cat $TOKEN_FILE)" \
-     "https://iam.googleapis.com/v1/projects/$GOOGLE_CLOUD_PROJECT/serviceAccounts/$GOOGLE_APPLICATION_SERVICE_ACCOUNT"
-  echo "~~~ :gcloud: Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT} cleaned up"
+     "https://iam.googleapis.com/v1/projects/$GOOGLE_CLOUD_PROJECT/serviceAccounts/$GOOGLE_APPLICATION_SERVICE_ACCOUNT" || error=true
+  if [[ -n ${error:-} ]]; then
+    echo "!!! :gcloud: Failed to delete Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT}"
+    # Send Slack notification about the failure
+    . "$CWD/../libs/slack"
+    send_message
+  else
+    echo "~~~ :gcloud: Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT} cleaned up"
+  fi
 fi
 
 if [[ -v BUILDKITE_OIDC_TMPDIR ]]; then
@@ -16,3 +25,5 @@ if [[ -v BUILDKITE_OIDC_TMPDIR ]]; then
 
   echo "Removed credentials from $BUILDKITE_OIDC_TMPDIR"
 fi
+
+set -eu
