feature: Add service account login credentials (#10)
* Add service account login credentials feature

* Update hooks/environment

Co-authored-by: Victor Martinez <victormartinezrubio@gmail.com>

* Redact the oidc token, ensure the availability of the token in the pre-exit command and apply some reviewer comments

* Improve plugin structure

* Add catalog info

* Add buildkite pipeline to test the plugin

* Parameterize slack send message and add labels in the service account description since it's not supported yet by this kind of resources

* Fix token file path parser in pre-exit

* Fix token file path parser in pre-exit truly

* Set the fight hash to avoid colisions and fix the service account name

* Fix the name of the repository

---------

Co-authored-by: Victor Martinez <victormartinezrubio@gmail.com>

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -1,9 +1,44 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set +eu
+
+CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+SLACK_CHANNEL="${BUILDKITE_PLUGIN_OBLT_GOOGLE_AUTH_SLACK_CHANNEL:-"#observablt-bots"}"
+
+if [[ -n ${GOOGLE_APPLICATION_SERVICE_ACCOUNT:-} ]]; then
+  echo "~~~ :gcloud: Cleaning up Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT}"
+  TOKEN_FILE=$(cat $GOOGLE_APPLICATION_CREDENTIALS | jq -r '.credentials_source.file')
+
+  curl -X DELETE \
+     -H "Authorization: Bearer $(cat $TOKEN_FILE)" \
+     "https://iam.googleapis.com/v1/projects/$GOOGLE_CLOUD_PROJECT/serviceAccounts/$GOOGLE_APPLICATION_SERVICE_ACCOUNT" || error=true
+  
+  if [[ -n ${error:-} ]]; then
+    echo "!!! :gcloud: Failed to delete Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT}"
+
+    # Send Slack notification and set a Buildkite annotation about the failure
+
+    # shellcheck disable=SC1091
+    . "$CWD/../libs/slack"
+
+    read -r -d '' MESSAGE << EOM
+:fire: Google Auth Buildkite Plugin cleanup process failed: <$BUILDKITE_BUILD_URL|Execution logs>! 
+Check current service accounts executing \`gcloud iam service-accounts list --project=elastic-observability-ci --filter=Email:bk-plugin-sa\`. 
+Remove manually! :fire:
+EOM
+
+    buildkite-agent annotate "$MESSAGE" --style "warning" --context "gcloud-auth-service-account-cleanup-failure"
+
+    send_message $SLACK_CHANNEL "$MESSAGE"
+  else
+    echo "~~~ :gcloud: Service Account ${GOOGLE_APPLICATION_SERVICE_ACCOUNT} cleaned up"
+  fi
+fi
 
 if [[ -v BUILDKITE_OIDC_TMPDIR ]]; then
   rm -rf "$BUILDKITE_OIDC_TMPDIR"
 
   echo "Removed credentials from $BUILDKITE_OIDC_TMPDIR"
 fi
+
+set -eu
