Add clear failure message if not gcloud optional requirement is installed, document why we use gcloud instead of Rest API calls and set the optional gcloud dependency information

diff --git a/libs/gcloud b/libs/gcloud
--- a/libs/gcloud
+++ b/libs/gcloud
@@ -3,11 +3,23 @@
 set -euo pipefail
 
 # Functions for Google Cloud Service Account management
+#
+# This script is using gcloud instead of REST API calls to manage service accounts
+# to avoid dealing with OAuth tokens and scopes. 
+# If the command `gcloud auth print-access-token` could be translated into an API call,
+# the script could be refactored to avoid the dependency on gcloud CLI.
 
 LABEL_ORG="obs"
 LABEL_DIVISION="engineering"
 LABEL_TEAM="eng-productivity"
 LABEL_EPHEMERAL="true"
+
+function check_if_gcloud_installed() {
+  if ! command -v gcloud &> /dev/null; then
+    echo ":bk-status-failed: gcloud could not be found. Please install the Google Cloud SDK to use this plugin with service accounts."
+    exit 1
+  fi
+}
 
 # Create the service account
 # Arguments:
@@ -52,7 +64,7 @@ function create_service_account_key() {
   local -r SA_ACCOUNT="$1"
   local -r PROJECT_ID="$2"
   local -r SA_KEY_FILE="$3"
-  
+
   gcloud iam service-accounts keys create "$SA_KEY_FILE" \
     --iam-account="$SA_ACCOUNT" \
     --project="$PROJECT_ID"
